version: 1.0.2.{build}

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2019
configuration: Release

clone_depth: 1
clone_folder: C:\build

build:
  project: SDK-CPP.sln
  parallel: true
  verbosity: minimal