name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v1
        
      - name: Build
        run: .\build.bat
